# Generated by Django 6.0.1 on 2026-03-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmissionResult',
        ),
    ]
