# Generated by Django 6.0.1 on 2026-03-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0002_delete_emissionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='transport_mode',
            field=models.CharField(default='car', max_length=50),
            preserve_default=False,
        ),
    ]
