# Generated by Django 6.0.1 on 2026-03-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0003_emissionrecord_transport_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='mode_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='secondary_origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='transport_mode',
            field=models.CharField(default='car', max_length=50),
        ),
    ]
