# Generated by Django 6.0.1 on 2026-03-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0004_emissionrecord_mode_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='days',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
